### ISSUE TITLE
Recent steam update changed downloads page

### ISSUE THREAD

**Issue by PopeThatSmokedCoke** [ungstein/OG-Steam-Library#2]
Steam received a somewhat sizable update which changed the downloads page for the skin
![Capture](https://user-images.githubusercontent.com/90521972/132955032-745861d1-e4ab-4e7b-9bde-725ab85e6f06.PNG)

**Comment by PopeThatSmokedCoke** [comment]
Apperently there is also a new menu called storage manager as well which is similar to the downloads page where the buttons are affected by the skin but the background is not, and for some reason it has two scroll bars side by side not sure if its because of the skin or thats how its supposed to be. Figured id upload a picture as well to keep them in one place.
![Capture](https://user-images.githubusercontent.com/90521972/133923997-6b97f330-90f1-40db-bb77-d0964c62ef26.PNG)

**Comment by ungstein** [comment]
I'm sure it's the skin at this point, but I don't have time to fix it. The problem with the way Valve has styled the web components of Steam is that instead of defining a handful of styles and referring to those throughout Steam (as is the case with steam.styles), they've gone and defined styles for *every single goddamn element*. This makes modding incredibly tedious. The way everything has been named with a unique id at the end like ".appdetailsfeatureicon_Container_1SIa8" suggests edits are being made using some kind of semi-automated editing software. I have been making my edits *by hand*. It's a team of paid developers using sophisticated software vs. me with a text editor. If anyone would like to suggest a better way to make edits, I am open.

**Comment by PopeThatSmokedCoke** [comment]
I'm not particularly knowledgable when it comes to programming but it sounds like the web elements are treated as individual pages so they are probably using different adresses for each component, similar to how you would design a website so they can be updated without affecting each other. Some common elements like the buttons and scroll bars are linked to a master. Not sure if this is usefull but you might try organizing the different pages similar to a website index, if i understood it right the devs themselves edit these elements seperatly as well from the looks of it, similar to how someone can make edits to webpages witjout affecting the homepage but certain elements would be carried from the master(homepage) to the children. Regardless thank you for making the skin and the work you've put in to it.

**Comment by ungstein** [comment]
I agree with what you are saying. I am no expert web dev either, nor have I done web dev professionally. It just seems there are many styles that are common throughout the interface that are defined for individual elements, which seems very inefficient and as I said previously, tedious to edit. Currently, the .css files are very helpfully named 0.css, 1.css, 2.css, 5.css and library.css. Originally there was another file named libraryroot.css which seems to have been split into multiple files. I would expect files to be named as per the "page" the styles apply to, e.g. "gameproperties.css, storagemanager.css", etc. This unintuitive naming/grouping, again, suggests a certain degree of automation. The whole thing needs a rewrite to be modder-friendly.

**Comment by ungstein** [comment]
Even something as simple as colours has been made needlessly complicated by using hex colours throughout, some varying just a couple of shades, instead of using easily searchable colour variables. I added these to OGSL, but I have to manually replace each and every defined hex colour with a variable which, again, is very time consuming.

**Comment by PopeThatSmokedCoke** [comment]
Your new beta for the downloads page seems to have affected the storage manager ass well apart from the install/Play button  everything seems fine.

![Capture](https://user-images.githubusercontent.com/90521972/140765305-aa843fcf-cf5b-4957-be46-3ac202fc2207.PNG)

**Comment by ungstein** [comment]
Thanks for trying the beta. The Storage Manager is skinned because I modded that, too. The Install/Play button was left intentionally, but I think I'll add a border to it. I'll close this now.
